
CREATE DATABASE LocadoraAPI;
GO
use LocadoraAPI;
GO

CREATE TABLE DBO.GENERO(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL,
	DtCriacao DATETIME2,
	ATIVO INT
);

CREATE TABLE DBO.FILME(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(200) NOT NULL,
    DTCRIACAO DATETIME2 NOT NULL,
    ATIVO INT NOT NULL,
	IDGENERO INT not null FOREIGN KEY REFERENCES GENERO(ID) 
);

CREATE TABLE DBO.LOCACAO(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CPF VARCHAR(14) NOT NULL,
	DTLOCACAO DATETIME2
);


CREATE TABLE DBO.LOCACAO_FILME(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_LOCACAO INT not null FOREIGN KEY REFERENCES LOCACAO(ID),
	ID_FILME INT not null FOREIGN KEY REFERENCES FILME(ID)
);


INSERT INTO DBO.GENERO(NOME, DtCriacao, ATIVO) VALUES('ACTION','20210304',1);

INSERT INTO DBO.FILME( NOME, DTCRIACAO, ATIVO, IDGENERO) VALUES ( 'BAD BOYS','20210304',1,1);